# Generated by Django 3.1.3 on 2022-04-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenusInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authName', models.CharField(max_length=20, verbose_name='菜单名称')),
                ('children', models.CharField(max_length=20, verbose_name='子级菜单')),
                ('path', models.CharField(max_length=256, verbose_name='菜单地址')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'tb_menus',
            },
        ),
    ]
