# Generated by Django 3.1.3 on 2022-04-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menusinfo',
            name='children',
        ),
        migrations.AddField(
            model_name='menusinfo',
            name='parent',
            field=models.CharField(max_length=20, null=True, verbose_name='父级菜单'),
        ),
    ]
