# Generated by Django 3.1.3 on 2022-04-12 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220412_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentmenusinfo',
            name='children',
        ),
        migrations.AddField(
            model_name='childrenmenusinfo',
            name='parent_id',
            field=models.ForeignKey(null=b'I00\n', on_delete=django.db.models.deletion.CASCADE, to='api.parentmenusinfo', verbose_name='二级菜单'),
            preserve_default=b'I00\n',
        ),
    ]
