# Generated by Django 3.1.3 on 2022-04-12 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220412_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childrenmenusinfo',
            name='parent_id',
            field=models.ForeignKey(null=b'I00\n', on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.parentmenusinfo', verbose_name='二级菜单'),
        ),
    ]
